on: [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing the new action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Npm Install
        run: npm install
      - name: Run lint
        run: npm run lint-ci
      - name: File Notitifier Step #runs the action in this repo
        id: slack-notifier
        uses: ./
        with:
          file: 'Translations.xml'
          slack-title: 'New Keys'
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack-channel: '#action_test'
          github-token: ${{ github.token }}
      - name: Get the output did notify
        run: echo "Notified slack ${{ steps.slack-notifier.outputs.didNotify }}"