on: [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing the new action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        id: slack-notifier
        uses: ./
        with:
          file: 'Translations.xml'
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack-channel: '#action_test'
          github-token: ${{ github.token }}
      - name: Get the output did notify
        run: echo "Notified slack ${{ steps.slack-notifier.outputs.didNotify }}"